String str = BRANCH_NAME == "master" ? "0 0 * * *" : ""

pipeline{
    agent {
        kubernetes {
            cloud 'kubernetes-new'
            inheritFrom 'centos-docker-node'
        }
    }
    triggers {
        cron(str)
    }
    options{
        ansiColor('xterm')
        disableConcurrentBuilds(abortPrevious: true)
        timestamps()
        skipDefaultCheckout(true)
        buildDiscarder(logRotator(numToKeepStr:'10'))
    }
    stages{
        stage("build"){
            steps{
                cleanWs()
                checkout scm
                dir("ciscript"){ git url: 'git@git.yasdb.com:luweikang/ciscript.git', branch: "flink" }
                sh """
                set -ex
                bash ${WORKSPACE}/ciscript/L2_L3_docker/L2_kafka_compile_pkg.sh kafka_Merge_Build ${BRANCH_NAME}
                """
            }
        }
    }
    post{
        always {
            findText(
                textFinders: [
                    textFinder(
                        alsoCheckConsoleOutput: true,
                        regexp: '(Build|Install|Test)\\s[a-zA-Z-]+[\\s[a-zA-Z]+\\s]?failed|make.*:.+\\sError\\s[0-9]+|Test Run Error!|error: unknown type name|Segmentation fault|error: could not compile|compilation terminated|configure: error:|command not found'
                    )
                ]
            )
            archiveArtifacts artifacts: 'kafka_pkg/*', excludes: '*.md5', followSymlinks: false, onlyIfSuccessful: true
        }
        failure {
            updateGitlabCommitStatus name: 'build',state: 'failed'
        }
        success {
            updateGitlabCommitStatus name: 'build',state: 'success'
        }
    }
}